const mongoose = require('mongoose');

const profileSchema = new mongoose.Schema({
    firstName: String,
    lastName: String,
    email: { type: String, required: true, unique: true },
    phone: String,
    dateOfBirth: Date,
    gender: String,
    maritalStatus: String,
    height: String,
    weight: Number,
    bodyType: String,
    skinTone: String,
    physicalDisability: String,
    disabilityDetails: String,
    bloodGroup: String,
    hairTypeColor: String,
    eyeColor: String,
    medicalConditions: String,
    pastSurgeries: String,
    surgeryDetails: String,
    piercingsTattoos: String,
    city: String,
    state: String,
    country: String,
    pincode: String,
    religion: String,
    caste: String,
    subCaste: String,
    community: String,
    birthTime: String,
    dateOfBirth: { type: Date, required: true },    education: String,
    occupation: String,
    employer: String,
    annualIncome: Number,
    workLocation: String,
    hobbies: [String],
    interests: [String],
    diet: String,
    smoking: String,
    drinking: String,
    profileVisibility: String,
    contactPreference: String,
    showPhone: Boolean,
    showEmail: Boolean,
    linkedin: String,
    instagram: String,
    aadharCard: String, // Store as URL or base64 string
    educationCertificate: String,
    incomeCertificate: String,
    aboutYourself: String,
    motherTongue: String,
    subCommunity: String,
    familyType: String,
    familyStatus: String,
    familyValues: String,
    fatherOccupation: String,
    motherOccupation: String,
    brothers: Number,
    sisters: Number,
    familyContact: String,
    fitnessLevel: String
}, { timestamps: true });

module.exports = mongoose.model('UserProfile', profileSchema);
